language: cpp

os: linux

dist: focal

addons:
  apt:
    packages:
      - g++
      - clang
      - cmake
      - make
      - bison
      - flex
      - ronn
      - bzip2
      - pkg-config
      - binutils-dev
      - libboost-all-dev
      - libevent-dev
      - libdouble-conversion-dev
      - libgoogle-glog-dev
      - libgflags-dev
      - libiberty-dev
      - liblz4-dev
      - liblzma-dev
      - libzstd-dev
      - libsnappy-dev
      - libjemalloc-dev
      - libssl-dev
      - libunwind-dev
      - libfmt-dev
      - libfuse3-dev
      - libsparsehash-dev
      - zlib1g-dev

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake -DWITH_TESTS=1 ..

script:
  - make -j$(nproc)
  - make test
  - make package_source
  - tar xvf dwarfs-*.tar.bz2
  - cd dwarfs-*
  - mkdir build
  - cd build
  - cmake -DWITH_TESTS=1 ..
  - make -j$(nproc)
  - make test
